version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building project..."
      - mvn package
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - target/*.war
